/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-04 at 09:10:22 UTC 
 * Modify at your own risk.
 */

package com.dat255.risk.network.testendpoint.model;

/**
 * Model definition for ServletContext.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the testendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ServletContext extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Enumeration attributeNames;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String contextPath;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Enumeration initParameterNames;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer majorVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer minorVersion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String serverInfo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String servletContextName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Enumeration servletNames;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Enumeration servlets;

  /**
   * @return value or {@code null} for none
   */
  public Enumeration getAttributeNames() {
    return attributeNames;
  }

  /**
   * @param attributeNames attributeNames or {@code null} for none
   */
  public ServletContext setAttributeNames(Enumeration attributeNames) {
    this.attributeNames = attributeNames;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContextPath() {
    return contextPath;
  }

  /**
   * @param contextPath contextPath or {@code null} for none
   */
  public ServletContext setContextPath(java.lang.String contextPath) {
    this.contextPath = contextPath;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Enumeration getInitParameterNames() {
    return initParameterNames;
  }

  /**
   * @param initParameterNames initParameterNames or {@code null} for none
   */
  public ServletContext setInitParameterNames(Enumeration initParameterNames) {
    this.initParameterNames = initParameterNames;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMajorVersion() {
    return majorVersion;
  }

  /**
   * @param majorVersion majorVersion or {@code null} for none
   */
  public ServletContext setMajorVersion(java.lang.Integer majorVersion) {
    this.majorVersion = majorVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMinorVersion() {
    return minorVersion;
  }

  /**
   * @param minorVersion minorVersion or {@code null} for none
   */
  public ServletContext setMinorVersion(java.lang.Integer minorVersion) {
    this.minorVersion = minorVersion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getServerInfo() {
    return serverInfo;
  }

  /**
   * @param serverInfo serverInfo or {@code null} for none
   */
  public ServletContext setServerInfo(java.lang.String serverInfo) {
    this.serverInfo = serverInfo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getServletContextName() {
    return servletContextName;
  }

  /**
   * @param servletContextName servletContextName or {@code null} for none
   */
  public ServletContext setServletContextName(java.lang.String servletContextName) {
    this.servletContextName = servletContextName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Enumeration getServletNames() {
    return servletNames;
  }

  /**
   * @param servletNames servletNames or {@code null} for none
   */
  public ServletContext setServletNames(Enumeration servletNames) {
    this.servletNames = servletNames;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Enumeration getServlets() {
    return servlets;
  }

  /**
   * @param servlets servlets or {@code null} for none
   */
  public ServletContext setServlets(Enumeration servlets) {
    this.servlets = servlets;
    return this;
  }

  @Override
  public ServletContext set(String fieldName, Object value) {
    return (ServletContext) super.set(fieldName, value);
  }

  @Override
  public ServletContext clone() {
    return (ServletContext) super.clone();
  }

}
